version: 2

defaults: &defaults
  docker:
  - image: golang:1.12-stretch
  working_directory: /go/src/go.mercari.io/go-emv-code

jobs:
  test:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Run test
        command: |
          make test
  coverage:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Run test and collect coverages
        command: |
          make coverage
    - run:
        name: Upload coverages to codecov
        command: |
          bash <(curl -s https://codecov.io/bash)
  reviewdog:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Run reviewdog
        command: |
          make reviewdog

workflows:
  version: 2
  build-workflow:
    jobs:
    - test
    - coverage
    - reviewdog
