version: 2.1

executors:
  golang-stretch:
    docker:
      - image: golang:1.12-stretch
    environment:
      GO111MODULE: "on"
    shell: /bin/bash -eu -o pipefail
    working_directory: /go/src/go.mercari.io/mercari/go-emv-code

jobs:
  test:
    executor: golang-stretch
    steps:
    - checkout
    - run:
        name: Run test
        command: |
          make test

  coverage:
    executor: golang-stretch
    steps:
    - checkout
    - run:
        name: Run test and collect coverages
        command: |
          make coverage
    - run:
        name: Upload coverages to codecov
        command: |
          bash <(curl -s https://codecov.io/bash)

  reviewdog:
    executor: golang-stretch
    steps:
    - checkout
    - run:
        name: Run reviewdog
        command: |
          make reviewdog

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
      - coverage
      - reviewdog:
          filters:
            branches:
              ignore:
                - master
